all: server-bad server-good server-best

server-bad: server-bad.o lib.o
server-good: server-good.o lib.o
server-best: server-best.o lib.o

server-bad.o: server-bad.c
server-good.o: server-good.c
server-best.o: server-best.c
lib.o: lib.c
